name: stak-notebooks
channels:
  - http://ssb.stsci.edu/astroconda
dependencies:
  - numpy
  - scipy
  - astropy
  - numpydoc
  - nbconvert>=5.0.0
  - sphinx>=1.5
  - pip:
    - sphinx_rtd_theme
    - stsci_rtd_theme

